version: '4.33.1'

services:
  postgres:
    container_name: terracota_db
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: terracote_db